trigger:
  branches:
    include:
      - main

  paths:
    include:
      - project-env/dev/*
      - modules/*

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
- name: AWS_SERVICE_CONNECTION
  value: Aws-connection
- name: TF_VERSION
  value: '1.8.5'
- name: TF_WORKING_DIR
  value: project-env/dev
- name: TF_STATE_BUCKET
  value: suren2345
- name: TF_STATE_KEY
  value: project-env/dev/terraform.tfstate
- name: TF_STATE_REGION
  value: ap-south-1

stages:
########################################################
# Terraform Plan
########################################################
- stage: Plan
  displayName: Terraform Plan
  jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)
    - task: AWSShellScript@1
      displayName: Debug Repository
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(TF_STATE_REGION)
        scriptType: inline
        inlineScript: |
          echo "Current Directory"
          pwd
          echo "Repository Structure"
          ls -R
          echo "Move to Terraform Directory"
          cd $(TF_WORKING_DIR)
          pwd
          echo "Terraform Files"
          find . -name "*.tf"
          echo "Modules"
          ls ../../modules

    - task: AWSShellScript@1
      displayName: Terraform Init
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(TF_STATE_REGION)
        scriptType: inline
        inlineScript: |
          cd $(TF_WORKING_DIR)
          terraform init -reconfigure \
            -backend-config="bucket=$(TF_STATE_BUCKET)" \
            -backend-config="key=$(TF_STATE_KEY)" \
            -backend-config="region=$(TF_STATE_REGION)"

    - script: |
        cd $(TF_WORKING_DIR)
        terraform fmt -check
        terraform validate
      displayName: Terraform Validate

    - task: AWSShellScript@1
      displayName: Terraform Plan
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(TF_STATE_REGION)
        scriptType: inline
        inlineScript: |
          cd $(TF_WORKING_DIR)
          terraform plan -out=tfplan -input=false

    - task: PublishPipelineArtifact@1
      displayName: Publish Plan
      inputs:
        targetPath: $(TF_WORKING_DIR)/tfplan
        artifact: tfplan

########################################################
# Manual Approval
########################################################

- stage: Approval
  displayName: Manual Approval
  dependsOn: Plan
  jobs:
  - job: WaitForApproval
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        instructions: |
          Please review the Terraform Plan.
          Click Resume to continue.
        onTimeout: reject

########################################################
# Terraform Apply
########################################################

- stage: Apply
  displayName: Terraform Apply
  dependsOn: Approval
  condition: succeeded()
  jobs:
  - job: TerraformApply
    steps:
    - checkout: self
    - download: current
      artifact: tfplan
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: AWSShellScript@1
      displayName: Terraform Init
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(TF_STATE_REGION)
        scriptType: inline
        inlineScript: |
          cd $(TF_WORKING_DIR)
          terraform init -reconfigure \
            -backend-config="bucket=$(TF_STATE_BUCKET)" \
            -backend-config="key=$(TF_STATE_KEY)" \
            -backend-config="region=$(TF_STATE_REGION)"

    - task: AWSShellScript@1
      displayName: Terraform Apply
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION)
        regionName: $(TF_STATE_REGION)
        scriptType: inline
        inlineScript: |
          cd $(TF_WORKING_DIR)
          terraform apply -auto-approve $(Pipeline.Workspace)/tfplan/tfplan