trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_SERVICE_CONNECTION: 'Aws-connection'
  TF_VERSION: '1.8.5'
  TF_WORKING_DIR: 'project-env/dev'

stages:

#--------------------------------------------------------
# Stage 1 - Terraform Plan
#--------------------------------------------------------
- stage: Plan
  displayName: Terraform Plan
  jobs:
  - job: TerraformPlan
    displayName: Terraform Plan
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '$(TF_VERSION)'
    - task: AWSShellScript@1
      displayName: Debug Repository
      inputs:
        awsCredentials: '$(AWS_SERVICE_CONNECTION)'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          echo "Current Directory"
          pwd
          echo "Repository Structure"
          ls -R
          echo "Working Directory"
          cd $(TF_WORKING_DIR)
          pwd
          echo "Terraform Files"
          ls -la
          find . -name "*.tf"
          echo "Modules"
          ls ../../modules

    - task: AWSShellScript@1
      displayName: Terraform Init
      inputs:
        awsCredentials: '$(AWS_SERVICE_CONNECTION)'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          cd $(TF_WORKING_DIR)
          terraform init -reconfigure

    - script: |
        cd $(TF_WORKING_DIR)
        terraform fmt -check
      displayName: Terraform Format
    - script: |
        cd $(TF_WORKING_DIR)
        terraform validate
      displayName: Terraform Validate
    - task: AWSShellScript@1
      displayName: Terraform Plan
      inputs:
        awsCredentials: '$(AWS_SERVICE_CONNECTION)'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          cd $(TF_WORKING_DIR)
          terraform plan -out=tfplan
    - task: PublishPipelineArtifact@1
      displayName: Publish tfplan
      inputs:
        targetPath: '$(TF_WORKING_DIR)/tfplan'
        artifact: tfplan