trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.12.2'
  workingDirectory: 'azure-infra-project/dev-proj'

stages:
- stage: TerraformPlan
  jobs:
  - job: Plan
    steps:
    - checkout: self
    - script: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://releases.hashicorp.com/terraform/$(TERRAFORM_VERSION)/terraform_$(TERRAFORM_VERSION)_linux_amd64.zip
        unzip terraform_$(TERRAFORM_VERSION)_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform version
      displayName: "Install Terraform"
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'Aws-connection'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          cd $(workingDirectory)
          terraform init
          terraform validate
          terraform plan -out=tfplan
    - publish: $(workingDirectory)/tfplan
      artifact: tfplan

- stage: Approval
  jobs:
  - job: Wait
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Approve Deployment'

- stage: TerraformApply
  dependsOn: Approval
  jobs:
  - job: Apply
    steps:
    - checkout: self
    - download: current
      artifact: tfplan
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(terraformVersion)
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-connection'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          cd $(workingDirectory)
          terraform init
          terraform apply -auto-approve tfplan